#!/bin/bash

etcdctl put apt/sum/netflow_"$1" $2
etcdctl put apt/sum/netflowd_"$1" $2
etcdctl put apt/sum/netflowp_"$1" $2
etcdctl put apt/sum/netflowip_"$1" $2
etcdctl put apt/sum/netflowipd_"$1" $2
etcdctl put apt/sum/netflowipp_"$1" $2
etcdctl put apt/sum/netflowdp_"$1" $2


